### ISSUE TITLE
Envoy 1.14.5 compatibility

### ISSUE THREAD

**Issue by stoader** [proxy-wasm/proxy-wasm-cpp-sdk#66]
Can you provide some details on what branch/tag/commit points to the latest commit for Envoy 1.14.5? My understanding is that the `envoy-release/v1.15` is for Envoy 1.15 and the SDK built from this branch is not compatible with Envoy 1.14.5

**Comment by PiotrSikora** [comment]
I'm afraid that this repo was created after we shipped Istio 1.6 (based on Envoy 1.14.x), and it was first used in Istio 1.7 (based on Envoy 1.15.x), so there is no version of the SDK here that's guaranteed to work with such old release.

Your best bet would be using [api/wasm/cpp from Istio 1.6](https://github.com/istio/envoy/tree/release-1.6/api/wasm/cpp/), but so many bugs were fixed since then, that you should really consider using more recent version.

**Comment by stoader** [comment]
Thank you for the quick reponse.

**Comment by stoader** [comment]
@PiotrSikora I tried to build our WASM filter as described here: https://github.com/istio/envoy/tree/release-1.6/api/wasm/cpp#compiling-with-the-docker-build-image

The build fails with the following error:
```
Adding directories to PATH:
PATH += /root/emsdk
PATH += /root/emsdk/upstream/emscripten
PATH += /root/emsdk/node/12.18.1_64bit/bin

Setting environment variables:
PATH = /root/emsdk:/root/emsdk/upstream/emscripten:/root/emsdk/node/12.18.1_64bit/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
EMSDK = /root/emsdk
EM_CONFIG = /root/emsdk/.emscripten
EM_CACHE = /root/emsdk/upstream/emscripten/cache
EMSDK_NODE = /root/emsdk/node/12.18.1_64bit/bin/node
fatal: not a git repository (or any parent up to mount point /)
```

Any idea what might be causing this?
